name: metadent_serving_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animations: ^2.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_localization: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  responsive_framework: ^0.1.9
  flutter_screenutil: ^5.4.0
  google_fonts: ^2.3.2
  blinking_text: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  